### PR TITLE
Add YCB object models

### LINKED ISSUE #1: Import YCB models from HSR gazebo package
The [tmc_wrs_gazebo](https://github.com/hsr-project/tmc_wrs_gazebo) package from Toyota has several YCB model meshes available under the [Creative Commons Attribution 4.0 International license](https://creativecommons.org/licenses/by/4.0/). Importing these models here would make this tool more useful.

The models can be found [here](https://github.com/hsr-project/tmc_wrs_gazebo/tree/master/tmc_wrs_gazebo_worlds/models). When importing the models, we should not forget to add the License information as described [here](https://github.com/hsr-project/tmc_wrs_gazebo/tree/master/tmc_wrs_gazebo_worlds#begins-with-the-name-ycb_).

Related to: #2

### PR DESCRIPTION
**Pull request by Sushant-Chavan**
This PR adds the YCB 3D model meshes from Toyota's [tmc_wrs_gazebo](https://github.com/hsr-project/tmc_wrs_gazebo) repository. It also provides a demo launch file to view all the YCB models in RViz.

To view all the YCB models build the package and execute the below command:
```
roslaunch rviz_3d_object_visualizer demo.launch
```

## Changelog

* Imported all the YCB models from the [tmc_wrs_gazebo](https://github.com/hsr-project/tmc_wrs_gazebo) repository
* Configured the text offset for several classes.
* Extended the `demo.launch` to support visualizing the YCB classes bu default.
* Implemented a new node `demo_ycb` for visualizing all the YCB objects. 

Closes #1 

## Checklist:

- [x] My code doesn't contain unnecessary comment blocks (e.g. unused code, templates of `package.xml` or `CMakeLists.txt`)
- [x] I have updated the `package.xml` and `CMakeLists.txt` with the correct dependencies.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by af-a — APPROVED** [review]

**Review by af-a — COMMENTED** [review]
I have noticed a minor problem. If the RViz window launched by `demo.launch` is closed manually without killing the node from the terminal, the node does not get killed cleanly (either says "rviz_3d_object_visualizer_demo-2 process has died", or escalates to SIGTERM and SIGKILL. If the node is killed first, no issue arises.

@Sushant-Chavan have you encountered this?

**Comment by alex-mitrevski** [comment]
@Sushant-Chavan Before merging the changes to `master`, I would only suggest renaming the directory names of the YCB models so that they don't include `ycb_###` as a prefix (I did the same with the YCB annotations that I recently added with https://github.com/b-it-bots/mas_perception_libs/pull/21).

**Comment by Sushant-Chavan** [comment]
@AhmedFaisal95  Yes I see it too. But looks like this issue is on the `master` branch itself and is independent of this PR. One possiblity could be the `panel` is incorectly shutdown. Could you create a separate issue for this?

**Comment by Sushant-Chavan** [comment]
> @Sushant-Chavan Before merging the changes to `master`, I would only suggest renaming the directory names of the YCB models so that they don't include `ycb_###` as a prefix (I did the same with the YCB annotations that I recently added with [b-it-bots/mas_perception_libs#21](https://github.com/b-it-bots/mas_perception_libs/pull/21)).

Do you mean rename `ycb_002_master_chef_can` to `master_chef_can`? Btw, what will be the class id stored in the object message? will it be a number like `002` or will it be a string like `002_master_chef_can`? That would be needed to be defined [here](https://github.com/b-it-bots/rviz_3d_object_visualizer/blob/d04767aa4f72f24387a841f177e7520057a9aa4e/config/object_mesh_categories.yaml#L14)

**Pull request merged**
